### ISSUE TITLE
Use the generic memcpy.c, memset.c, __set_thread_area.c files 

### ISSUE THREAD

**Issue by MaggieYingYi** [SNSystems/musl-prepo#2]
This issue is spin off from the Paul's question https://github.com/MaggieYingYi/musl-prepo/pull/1#discussion_r620256963.

The task involves the use of the generic memcpy.c, memset.c, __set_thread_area.c file instead of the target dependent assembling code.

**Comment by paulhuggett** [comment]
Given that the [pull request[(https://github.com/SNSystems/musl-prepo/pull/3) has been merged, can this issue be closed?

**Comment by MaggieYingYi** [comment]
Yes, closing now. Thanks.
